🛠 Fix gsp redirect during pre-render
Error: `redirect` can not be returned from
getStaticProps during prerendering

Solution:
Remove sign-in page since we're moving sign-in function to index page